---
- name: Update apt cache
  become: yes
  apt: update-cache=yes
  tags: common

- name: Repos directory
  become: yes
  file: path=/home/vagrant/repos/ state=directory owner=vagrant group=vagrant

- name: Install dev packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - vim
    - curl
    - git
    - htop
