---
- name: Add Percona apt signing key
  sudo: yes
  apt_key: url=http://www.percona.com/downloads/RPM-GPG-KEY-percona state=present

- name: Add Percona repository
  sudo: yes
  apt_repository: repo='deb http://repo.percona.com/apt trusty main' state=present

- name: Add Percona source repository
  sudo: yes
  apt_repository: repo='deb-src http://repo.percona.com/apt trusty main' state=present

- name: Update apt cache
  sudo: yes
  apt: update_cache=yes

- name: Install Percona packages
  sudo: yes
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - percona-server-common-5.6
    - percona-server-client-5.6
    - percona-server-server-5.6
