php_build_prefix: /usr/local
php_build_options: --prefix="{{ php_build_prefix }}" \
    --enable-soap \
    --enable-bcmath \
    --with-mcrypt \
    --with-xsl \
    --enable-mbstring \
    --with-curl \
    --with-gd \
    --with-jpeg-dir \
    --with-png-dir \
    --enable-intl \
    --enable-fpm \
    --with-openssl \
    --with-pdo-mysql \
    --with-mysql-sock=/var/run/mysqld/mysqld.sock \
    --enable-zip \
    --with-zlib \
    --with-zlib-dir
