- name: Install Packages Needed To Compile PHP 7
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - g++
    - libxml2-dev
    - libcurl4-openssl-dev
    - libjpeg8-dev
    - libpng12-dev
    - icu-devtools
    - libicu-dev
    - libmcrypt-dev
    - libxslt1-dev

- name: Ensure src directory exists with proper permissions
  sudo: yes
  file: path=/home/vagrant/src/ state=directory owner=vagrant

- name: Download PHP 7.0.0 src
  sudo: no
  get_url: url=http://php.net/get/php-7.0.0.tar.bz2/from/this/mirror dest=/home/vagrant/src/php-7.0.0.tar.bz2
  register: download

- name: Unpack PHP 7.0.0 src tarball
  sudo: no
  unarchive: src=/home/vagrant/src/php-7.0.0.tar.bz2 dest=/home/vagrant/src/ copy=no
  when: download.changed

- name: Configure the build
  sudo: no
  shell: ./configure {{ php_build_options }}
  args:
    chdir: /home/vagrant/src/php-7.0.0/
  register: configure

- name: Build PHP7
  sudo: no
  shell: make
  args:
    chdir: /home/vagrant/src/php-7.0.0/
  register: make
  when: configure.changed

- name: Install PHP7
  sudo: yes
  shell: make install
  args:
    chdir: /home/vagrant/src/php-7.0.0/
  when: make.changed

- name: PHP-FPM service
  sudo: yes
  shell: cp sapi/fpm/init.d.php-fpm /etc/init.d/php-fpm && chmod +x /etc/init.d/php-fpm && update-rc.d php-fpm defaults
  args:
    chdir: /home/vagrant/src/php-7.0.0/
  notify: start php-fpm
  when: download.changed

- name: php.ini
  sudo: yes
  template: src=php.ini
            dest=/usr/local/lib/php.ini
  notify: reload php-fpm

- name: php-fpm - magento2
  sudo: yes
  template: src=php-fpm-magento2.conf
            dest=/usr/local/etc/php-fpm.d/magento2.conf

- name: php-fpm
  sudo: yes
  template: src=php-fpm.conf
            dest=/usr/local/etc/php-fpm.conf
  notify: reload php-fpm

- include: xdebug.yml
