- name: Install Packages Needed To Compile PHP 7
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - g++
    - libxml2-dev
    - libcurl4-openssl-dev
    - libjpeg8-dev
    - libpng12-dev
    - icu-devtools
    - libicu-dev
    - libmcrypt-dev
    - libxslt1-dev

- name: Create src directory
  sudo: no
  file: path=/home/vagrant/src/ state=directory owner=vagrant

- name: Download PHP 7.0.0 src
  sudo: no
  get_url: url=http://php.net/get/php-7.0.0.tar.bz2/from/this/mirror dest=/home/vagrant/src/php-7.0.0.tar.bz2

- name: Unpack PHP 7.0.0 src tarball
  sudo: no
  unarchive: src=/home/vagrant/src/php-7.0.0.tar.bz2 dest=/home/vagrant/src/ copy=no

- name: Configure the build
  sudo: no
  shell: ./configure --prefix=/usr/local \
    --enable-soap \
    --enable-bcmath \
    --with-mcrypt \
    --with-xsl \
    --enable-mbstring \
    --with-curl \
    --with-gd \
    --with-jpeg-dir \
    --with-png-dir \
    --enable-intl \
    --enable-fpm \
    --with-openssl \
    --with-pdo-mysql \
    --with-mysql-sock=/var/run/mysqld/mysqld.sock \
    --enable-zip \
    --with-zlib \
    --with-zlib-dir
  args:
    chdir: /home/vagrant/src/php-7.0.0/

- name: Build PHP7
  sudo: no
  shell: make
  args:
    chdir: /home/vagrant/src/php-7.0.0/

- name: Install PHP7
  sudo: yes
  shell: make install
  args:
    chdir: /home/vagrant/src/php-7.0.0/