- name: Xdebug - autoconf
  sudo: yes
  apt: pkg=autoconf state=latest

- name: Xdebug - Ensure src directory exists with proper permissions
  sudo: yes
  file: path=/home/vagrant/src/ state=directory owner=vagrant

- name: Xdebug - Download Xdebug 2.4.0rc3 src
  sudo: no
  get_url: url=http://xdebug.org/files/xdebug-2.4.0rc3.tgz dest=/home/vagrant/src/xdebug-2.4.0rc3.tgz

- name: Xdebug - Create a directory for extracting archive
  sudo: no
  file: path=/home/vagrant/src/xdebug-2.4.0rc3/ state=directory

- name: Xdebug - Unpack Xdebug 2.4.0rc3 src tarball
  sudo: no
  unarchive: src=/home/vagrant/src/xdebug-2.4.0rc3.tgz dest=/home/vagrant/src/xdebug-2.4.0rc3/ copy=no

- name: Xdebug - Build
  sudo: no
  shell: phpize && ./configure && make
  args:
    chdir: /home/vagrant/src/xdebug-2.4.0rc3/xdebug-2.4.0RC3/

- name: Xdebug - Install
  sudo: yes
  shell: make install
  args:
    chdir: /home/vagrant/src/xdebug-2.4.0rc3/xdebug-2.4.0RC3/
