---
- name: Get composer checksum
  get_url:
    url: https://composer.github.io/installer.sig
    dest: /home/vagrant/composer-installer.sig

- name: Download installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /home/vagrant/composer-setup.php
    checksum: "sha384:{{ lookup('file', '/home/vagrant/composer-installer.sig') }}"

- name: Delete checksum file
  file: path=/home/vagrant/composer-installer.sig state=absent

- name: Install
  become: true
  shell: php /home/vagrant/composer-setup.php --filename=composer --install-dir=/usr/local/bin

- name: Delete installer
  file: path=/home/vagrant/composer-setup.php state=absent
