---
- name: Set up a LEMP7 stack for Magento2 on Ubuntu 14.04
  hosts: all
  sudo: no
  sudo_user: root
  remote_user: vagrant
  vars_files:
    - env_vars/base.yml
  roles:
    - common
    - git
    - nginx
    - php7
    - composer
    - percona
    - redis
    - memcached
    - sexy-bash-prompt
    - magento2