---
- include: composer.yml

- name: Check if magento2 directoy exists
  stat: path=/home/vagrant/repos/magento2
  register: magento2_dir

- include: create.yml
  when: magento2_dir.stat.exists == False

- name: Check if magento2 is installed
  shell: mysql -u root -Ns -e "SELECT COUNT(DISTINCT table_name) FROM information_schema.columns WHERE table_schema = 'magento2'"
  become: true
  register: magento2_tables_count

- include: install.yml
  when: magento2_tables_count.stdout == "0"

- include: conf.yml
